DROP TABLE USER_TABLE CASCADE CONSTRAINTS;
DROP TABLE FLIGHT cascade constraints;
DROP TABLE AIRPORT cascade constraints;
DROP SEQUENCE flight_seq;
DROP SEQUENCE airport_seq;
CREATE SEQUENCE flight_seq START WITH 3000 INCREMENT BY 1;
CREATE SEQUENCE airport_seq START WITH 3000 INCREMENT BY 1;

CREATE TABLE USER_TABLE(
	EMAIL_ID VARCHAR(50),
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL,
	USER_TYPE VARCHAR(50),
	constraint USER_EMAIL_ID_PK primary key ( EMAIL_ID )
);
INSERT INTO USER_TABLE(EMAIL_ID,FIRST_NAME,LAST_NAME,PASSWORD,PHONE_NUMBER,USER_TYPE) VALUES('marcus@marcus.com','Marcus','Marcus','$2a$10$IC89N1FWTANctiAxeHfj7.FKpfEoTS2GIcPuKhIyUmC6qwFuvAw0y','1114445545','ADMIN');
INSERT INTO USER_TABLE(EMAIL_ID,FIRST_NAME,LAST_NAME,PASSWORD,PHONE_NUMBER,USER_TYPE) VALUES('Jack@infosys.com','Jack','Jack','$2a$10$IC89N1FWTANctiAxeHfj7.FKpfEoTS2GIcPuKhIyUmC6qwFuvAw0y','1114445545','ADMIN');
SELECT * FROM USER_TABLE;

CREATE TABLE FLIGHT(
 	FLIGHT_ID NUMBER(10),
    FLIGHT_TYPE VARCHAR2 (50) NOT NULL,
    FLIGHT_SIZE NUMBER(10) NOT NULL,
    SEATS_AVAILABLE NUMBER(10) NOT NULL,
    DATE_OF_DEPARTURE DATE NOT NULL,
    DATE_OF_ARRIVAL DATE NOT NULL,
    DESTINATION VARCHAR2(50) NOT NULL,
	FLIGHT_FARE NUMBER(10) NOT NULL,
	FLIGHT_TAX NUMBER(10) NOT NULL,
    AIRPORT_ID NUMBER(10),
    constraint FLIGHT_FLIGHT_ID_PK primary key ( FLIGHT_ID )
 );

	
	
CREATE TABLE AIRPORT(
    AIRPORT_ID NUMBER(10),
    NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    constraint AIRPORT_AIRPORT_ID_PK primary key ( AIRPORT_ID )
);
	
	
ALTER TABLE FLIGHT ADD CONSTRAINT AIRPORT_AIR_ID_FK FOREIGN KEY ( AIRPORT_ID ) REFERENCES AIRPORT( AIRPORT_ID );


INSERT INTO AIRPORT(AIRPORT_ID, NAME, CITY) VALUES(1000,'DFW','Dallas');
INSERT INTO AIRPORT(AIRPORT_ID, NAME, CITY) VALUES(1001,'SFO','San Francisco');

INSERT INTO FLIGHT(FLIGHT_ID, FLIGHT_TYPE, FLIGHT_SIZE, SEATS_AVAILABLE, DATE_OF_DEPARTURE, DATE_OF_ARRIVAL, DESTINATION, FLIGHT_FARE, FLIGHT_TAX, AIRPORT_ID) VALUES(2000, 'DOMESTIC', 999, 100, SYSDATE+1, SYSDATE+1,'New York', 250, 14, 1000);
INSERT INTO FLIGHT(FLIGHT_ID, FLIGHT_TYPE, FLIGHT_SIZE, SEATS_AVAILABLE, DATE_OF_DEPARTURE, DATE_OF_ARRIVAL, DESTINATION, FLIGHT_FARE, FLIGHT_TAX, AIRPORT_ID) VALUES(2001, 'DOMESTIC', 999, 100, SYSDATE+2, SYSDATE+2,'New York', 250, 14, 1000);
INSERT INTO FLIGHT(FLIGHT_ID, FLIGHT_TYPE, FLIGHT_SIZE, SEATS_AVAILABLE, DATE_OF_DEPARTURE, DATE_OF_ARRIVAL, DESTINATION, FLIGHT_FARE, FLIGHT_TAX, AIRPORT_ID) VALUES(2002, 'DOMESTIC', 999, 100, SYSDATE+1, SYSDATE+1,'Austin', 250, 14, 1001);
select * from ADMIN;
SELECT * FROM AIRPORT;
SELECT * FROM FLIGHT;
